#!/usr/bin/env bash
#Displays Best School 10 times
# but for the 9th iteration, displays Best School and then Hi on a new line.

Num=0

while [ $Num -lt 10 ]
do
	if [ $Num -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( Num++ ))
done
