#!/usr/bin/env bash
#Script that loops from 1 to 10
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

Num=0

while [ $Num -lt 10 ]
do
	if [ $Num -eq 3 ]
	then
		echo "bad luck"
	elif [ $Num -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( Num++ ))
done
